// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { BaseClient, ClientConfig } from "./shared/client";
import { CountryCodeAllowlist } from "./country_code_allowlist";
import { EmailTemplates } from "./emailtemplates";
import { Environments } from "./environments";
import { EventLogStreaming } from "./event_log_streaming";
import { JWTTemplates } from "./jwttemplates";
import { PasswordStrengthConfig } from "./passwordstrengthconfig";
import { Projects } from "./projects";
import { PublicTokens } from "./publictokens";
import { RBACPolicy } from "./rbacpolicy";
import { RedirectURLs } from "./redirecturls";
import { SDK } from "./sdk";
import { Secrets } from "./secrets";
import { TrustedTokenProfiles } from "./trustedtokenprofiles";

export class ManagementClient extends BaseClient {
  projects: Projects;
  countryCodeAllowlist: CountryCodeAllowlist;
  emailTemplates: EmailTemplates;
  environments: Environments;
  eventLogStreaming: EventLogStreaming;
  jwtTemplates: JWTTemplates;
  passwordStrengthConfig: PasswordStrengthConfig;
  publicTokens: PublicTokens;
  rbacPolicy: RBACPolicy;
  redirectURLs: RedirectURLs;
  sdk: SDK;
  secrets: Secrets;
  trustedTokenProfiles: TrustedTokenProfiles;

  constructor(config: ClientConfig) {
    super(config);

    this.projects = new Projects(this.fetchConfig);
    this.countryCodeAllowlist = new CountryCodeAllowlist(this.fetchConfig);
    this.emailTemplates = new EmailTemplates(this.fetchConfig);
    this.environments = new Environments(this.fetchConfig);
    this.eventLogStreaming = new EventLogStreaming(this.fetchConfig);
    this.jwtTemplates = new JWTTemplates(this.fetchConfig);
    this.passwordStrengthConfig = new PasswordStrengthConfig(this.fetchConfig);
    this.publicTokens = new PublicTokens(this.fetchConfig);
    this.rbacPolicy = new RBACPolicy(this.fetchConfig);
    this.redirectURLs = new RedirectURLs(this.fetchConfig);
    this.sdk = new SDK(this.fetchConfig);
    this.secrets = new Secrets(this.fetchConfig);
    this.trustedTokenProfiles = new TrustedTokenProfiles(this.fetchConfig);
  }
}
