// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

// Request type for `countryCodeAllowlist.getAllowedSMSCountryCodes`.
export interface GetAllowedSMSCountryCodesRequest {
  // ProjectSlug is the slug of the project for which to retrieve allowed SMS country codes.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
  environment_slug: string;
}

// Response type for `countryCodeAllowlist.getAllowedSMSCountryCodes`.
export interface GetAllowedSMSCountryCodesResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // A list of country codes that are allowed for SMS.
  country_codes: string[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `countryCodeAllowlist.getAllowedWhatsAppCountryCodes`.
export interface GetAllowedWhatsAppCountryCodesRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `countryCodeAllowlist.getAllowedWhatsAppCountryCodes`.
export interface GetAllowedWhatsAppCountryCodesResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // A list of country codes that are allowed for WhatsApp.
  country_codes: string[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `countryCodeAllowlist.setAllowedSMSCountryCodes`.
export interface SetAllowedSMSCountryCodesRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // A list of country codes to set as allowed for SMS.
  country_codes: string[];
}

// Response type for `countryCodeAllowlist.setAllowedSMSCountryCodes`.
export interface SetAllowedSMSCountryCodesResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // A list of country codes that are allowed for SMS.
  country_codes: string[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `countryCodeAllowlist.setAllowedWhatsAppCountryCodes`.
export interface SetAllowedWhatsAppCountryCodesRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // A list of country codes to set as allowed for WhatsApp.
  country_codes: string[];
}

// Response type for `countryCodeAllowlist.setAllowedWhatsAppCountryCodes`.
export interface SetAllowedWhatsAppCountryCodesResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // A list of country codes that are allowed for WhatsApp.
  country_codes: string[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class CountryCodeAllowlist {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * GetAllowedSMSCountryCodes retrieves the allowed SMS country codes for an environment.
   * @param params {@link GetAllowedSMSCountryCodesRequest}
   * @returns {@link GetAllowedSMSCountryCodesResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getAllowedSMSCountryCodes(
    params: GetAllowedSMSCountryCodesRequest
  ): Promise<GetAllowedSMSCountryCodesResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetAllowedSMSCountryCodesResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/allowed_country_codes/sms`,
      params: {},
    });
  }

  /**
   * GetAllowedWhatsAppCountryCodes retrieves the allowed WhatsApp country codes for an environment.
   * @param params {@link GetAllowedWhatsAppCountryCodesRequest}
   * @returns {@link GetAllowedWhatsAppCountryCodesResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getAllowedWhatsAppCountryCodes(
    params: GetAllowedWhatsAppCountryCodesRequest
  ): Promise<GetAllowedWhatsAppCountryCodesResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetAllowedWhatsAppCountryCodesResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/allowed_country_codes/whatsapp`,
      params: {},
    });
  }

  /**
   * SetAllowedSMSCountryCodes sets the allowed SMS country codes for an environment.
   * @param data {@link SetAllowedSMSCountryCodesRequest}
   * @returns {@link SetAllowedSMSCountryCodesResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async setAllowedSMSCountryCodes(
    data: SetAllowedSMSCountryCodesRequest
  ): Promise<SetAllowedSMSCountryCodesResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<SetAllowedSMSCountryCodesResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/allowed_country_codes/sms`,
      data: {
        country_codes: data.country_codes,
      },
    });
  }

  /**
   * SetAllowedWhatsAppCountryCodes sets the allowed WhatsApp country codes for an environment.
   * @param data {@link SetAllowedWhatsAppCountryCodesRequest}
   * @returns {@link SetAllowedWhatsAppCountryCodesResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async setAllowedWhatsAppCountryCodes(
    data: SetAllowedWhatsAppCountryCodesRequest
  ): Promise<SetAllowedWhatsAppCountryCodesResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<SetAllowedWhatsAppCountryCodesResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/allowed_country_codes/whatsapp`,
      data: {
        country_codes: data.country_codes,
      },
    });
  }
}
