// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface Environment {
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The slug of the project.
  project_slug: string;
  // Name is a human-readable name. This does not have to be unique.
  name: string;
  // The callback ID used in OAuth requests for the environment.
  oauth_callback_id: string;
  // CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
  cross_org_passwords_enabled: boolean;
  // Indicates whether user impersonation is enabled for the environment.
  user_impersonation_enabled: boolean;
  // ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
  zero_downtime_session_migration_url: string;
  /**
   * Indicates whether users in the environment who get locked out should automatically get an unlock email
   * magic link.
   */
  user_lock_self_serve_enabled: boolean;
  /**
   * UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
   * environment to be locked. Defaults to 10.
   */
  user_lock_threshold: number;
  /**
   * Represents the time in seconds that the user in the environment remains locked once the lock is set.
   * Defaults to 1 hour (3600 seconds).
   */
  user_lock_ttl: number;
  // The OpenID Configuration endpoint for Connected Apps for the environment.
  idp_authorization_url: string;
  /**
   * IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client
   * Registration (DCR) for Connected Apps.
   */
  idp_dynamic_client_registration_enabled: boolean;
  /**
   * IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients
   * created through Dynamic Client Registration (DCR).
   */
  idp_dynamic_client_registration_access_token_template_content: string;
  // The environment's type.
  type?: "LIVE" | "TEST" | string;
  // The ISO-8601 timestamp for when the resource was created.
  created_at?: string;
}

export interface Metrics {
  // The number of active users in the environment (only relevant for Consumer projects).
  user_count: number;
  /**
   * OrganizationCount is the number of active organizations in the environment (only relevant for B2B
   * projects).
   */
  organization_count: number;
  // MemberCount is the number of active members in the environment (only relevant for B2B projects).
  member_count: number;
  // M2MClientCount is the number of active M2M clients in the environment.
  m2m_client_count: number;
}

// Request type for `environments.create`.
export interface CreateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // Name is a human-readable name. This does not have to be unique.
  name: string;
  // The environment's type.
  type?: "LIVE" | "TEST" | string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug?: string;
  // CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
  cross_org_passwords_enabled?: boolean;
  // Indicates whether user impersonation is enabled for the environment.
  user_impersonation_enabled?: boolean;
  // ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
  zero_downtime_session_migration_url?: string;
  /**
   * Indicates whether users in the environment who get locked out should automatically get an unlock email
   * magic link.
   */
  user_lock_self_serve_enabled?: boolean;
  /**
   * UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
   * environment to be locked. Defaults to 10.
   */
  user_lock_threshold?: number;
  /**
   * Represents the time in seconds that the user in the environment remains locked once the lock is set.
   * Defaults to 1 hour (3600 seconds).
   */
  user_lock_ttl?: number;
  // The OpenID Configuration endpoint for Connected Apps for the environment.
  idp_authorization_url?: string;
  /**
   * IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client
   * Registration (DCR) for Connected Apps.
   */
  idp_dynamic_client_registration_enabled?: boolean;
  /**
   * IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients
   * created through Dynamic Client Registration (DCR).
   */
  idp_dynamic_client_registration_access_token_template_content?: string;
}

// Response type for `environments.create`.
export interface CreateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Environment contains the details for the newly created environment.
  environment: Environment;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `environments.delete`.
export interface DeleteRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `environments.delete`.
export interface DeleteResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `environments.getAll`.
export interface GetAllRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
}

// Response type for `environments.getAll`.
export interface GetAllResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Environments is the list of environments that belong to the specified project.
  environments: Environment[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `environments.getMetrics`.
export interface GetMetricsRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `environments.getMetrics`.
export interface GetMetricsResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Metrics contains various metrics for the environment.
  metrics: Metrics;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `environments.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `environments.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Environment contains the environment details.
  environment: Environment;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `environments.update`.
export interface UpdateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // Name is a human-readable name. This does not have to be unique.
  name?: string;
  // CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
  cross_org_passwords_enabled?: boolean;
  // Indicates whether user impersonation is enabled for the environment.
  user_impersonation_enabled?: boolean;
  // ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
  zero_downtime_session_migration_url?: string;
  /**
   * Indicates whether users in the environment who get locked out should automatically get an unlock email
   * magic link.
   */
  user_lock_self_serve_enabled?: boolean;
  /**
   * UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
   * environment to be locked. Defaults to 10.
   */
  user_lock_threshold?: number;
  /**
   * Represents the time in seconds that the user in the environment remains locked once the lock is set.
   * Defaults to 1 hour (3600 seconds).
   */
  user_lock_ttl?: number;
  // The OpenID Configuration endpoint for Connected Apps for the environment.
  idp_authorization_url?: string;
  /**
   * IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client
   * Registration (DCR) for Connected Apps.
   */
  idp_dynamic_client_registration_enabled?: boolean;
  /**
   * IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients
   * created through Dynamic Client Registration (DCR).
   */
  idp_dynamic_client_registration_access_token_template_content?: string;
}

// Response type for `environments.update`.
export interface UpdateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Environment contains the details for the updated environment.
  environment: Environment;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class Environments {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Creates a new environment in a project.
   * @param data {@link CreateRequest}
   * @returns {@link CreateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async create(data: CreateRequest): Promise<CreateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    return request<CreateResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments`,
      data: {
        name: data.name,
        type: data.type,
        environment_slug: data.environment_slug,
        cross_org_passwords_enabled: data.cross_org_passwords_enabled,
        user_impersonation_enabled: data.user_impersonation_enabled,
        zero_downtime_session_migration_url:
          data.zero_downtime_session_migration_url,
        user_lock_self_serve_enabled: data.user_lock_self_serve_enabled,
        user_lock_threshold: data.user_lock_threshold,
        user_lock_ttl: data.user_lock_ttl,
        idp_authorization_url: data.idp_authorization_url,
        idp_dynamic_client_registration_enabled:
          data.idp_dynamic_client_registration_enabled,
        idp_dynamic_client_registration_access_token_template_content:
          data.idp_dynamic_client_registration_access_token_template_content,
      },
    });
  }

  /**
   * Retrieves an environment.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(params.environment_slug)}`,
      params: {},
    });
  }

  /**
   * Retrieves all environments in a project.
   * @param params {@link GetAllRequest}
   * @returns {@link GetAllResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getAll(params: GetAllRequest): Promise<GetAllResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    return request<GetAllResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments`,
      params: {},
    });
  }

  /**
   * Updates the environment.
   * @param data {@link UpdateRequest}
   * @returns {@link UpdateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async update(data: UpdateRequest): Promise<UpdateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<UpdateResponse>(this.fetchConfig, {
      method: "PATCH",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(data.environment_slug)}`,
      data: {
        name: data.name,
        cross_org_passwords_enabled: data.cross_org_passwords_enabled,
        user_impersonation_enabled: data.user_impersonation_enabled,
        zero_downtime_session_migration_url:
          data.zero_downtime_session_migration_url,
        user_lock_self_serve_enabled: data.user_lock_self_serve_enabled,
        user_lock_threshold: data.user_lock_threshold,
        user_lock_ttl: data.user_lock_ttl,
        idp_authorization_url: data.idp_authorization_url,
        idp_dynamic_client_registration_enabled:
          data.idp_dynamic_client_registration_enabled,
        idp_dynamic_client_registration_access_token_template_content:
          data.idp_dynamic_client_registration_access_token_template_content,
      },
    });
  }

  /**
   * Deletes an environment.
   * @param data {@link DeleteRequest}
   * @returns {@link DeleteResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async delete(data: DeleteRequest): Promise<DeleteResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<DeleteResponse>(this.fetchConfig, {
      method: "DELETE",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(data.environment_slug)}`,
      data: {},
    });
  }

  /**
   * Retrieves metrics for an environment.
   * @param params {@link GetMetricsRequest}
   * @returns {@link GetMetricsResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getMetrics(params: GetMetricsRequest): Promise<GetMetricsResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetMetricsResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(params.environment_slug)}/metrics`,
      params: {},
    });
  }
}
