// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface DatadogConfig {
  // APIKey is the API key for submitting logs to a Datadog account.
  api_key: string;
  // Site is one of the supported DatadogSite constants.
  site?: "US" | "US3" | "US5" | "EU" | "AP1" | string;
}

export interface DatadogConfigMasked {
  // APIKeyLastFour is the last four characters of the API key in use.
  api_key_last_four: string;
  // Site is one of the supported DatadogSite constants.
  site?: "US" | "US3" | "US5" | "EU" | "AP1" | string;
}

export interface DestinationConfig {
  // Datadog configuration settings for the destination.
  datadog?: DatadogConfig;
  // Grafana Loki configuration settings for the destination.
  grafana_loki?: GrafanaLokiConfig;
}

export interface DestinationConfigMasked {
  // Datadog configuration settings for the destination.
  datadog?: DatadogConfigMasked;
  // Grafana Loki configuration settings for the destination.
  grafana_loki?: GrafanaLokiConfigMasked;
}

export interface EventLogStreaming {
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
  // DestinationConfig is the configuration for the destination to which to send events.
  destination_config?: DestinationConfig;
  // Indicates whether event log streaming is enabled or disabled for the environment.
  streaming_status?: "ACTIVE" | "DISABLED" | "PENDING" | string;
}

export interface EventLogStreamingMasked {
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
  // DestinationConfig is the configuration for the destination to which to send events.
  destination_config?: DestinationConfigMasked;
  // Indicates whether event log streaming is enabled or disabled for the environment.
  streaming_status?: "ACTIVE" | "DISABLED" | "PENDING" | string;
}

export interface GrafanaLokiConfig {
  // Hostname is the hostname of the Grafana Loki instance to which to send events.
  hostname: string;
  // Username is the username for authenticating the request to a Grafana Loki instance.
  username: string;
  // Password is the password for authenticating the request to a Grafana Loki instance.
  password: string;
}

export interface GrafanaLokiConfigMasked {
  // Hostname is the hostname of the Grafana Loki instance to which to send events.
  hostname: string;
  // Username is the username for authenticating the request to a Grafana Loki instance.
  username: string;
  // PasswordLastFour is the last four characters of the password in use.
  password_last_four: string;
}

// Request type for `eventLogStreaming.create`.
export interface CreateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
  // DestinationConfig is the configuration for the destination to which to send events.
  destination_config?: DestinationConfig;
}

// Response type for `eventLogStreaming.create`.
export interface CreateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // EventLogStreamingConfig is the configuration that was created.
  event_log_streaming_config: EventLogStreaming;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `eventLogStreaming.delete`.
export interface DeleteRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
}

// Response type for `eventLogStreaming.delete`.
export interface DeleteResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `eventLogStreaming.disable`.
export interface DisableRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
}

// Response type for `eventLogStreaming.disable`.
export interface DisableResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `eventLogStreaming.enable`.
export interface EnableRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
}

// Response type for `eventLogStreaming.enable`.
export interface EnableResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `eventLogStreaming.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
}

// Response type for `eventLogStreaming.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  /**
   * EventLogStreamingConfig is the event log streaming configuration, with sensitive values masked (e.g.,
   * APIKey, Password).
   */
  event_log_streaming_config: EventLogStreamingMasked;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `eventLogStreaming.update`.
export interface UpdateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // DestinationType is the type of destination to which to send events.
  destination_type?: "DATADOG" | "GRAFANA_LOKI" | string;
  // DestinationConfig is the configuration for the destination to which to send events.
  destination_config?: DestinationConfig;
}

// Response type for `eventLogStreaming.update`.
export interface UpdateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // EventLogStreamingConfig is the configuration that was updated.
  event_log_streaming_config: EventLogStreaming;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class EventLogStreaming {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Get retrieves an event log streaming config for an environment.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!params.destination_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "destination_type cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/event_log_streaming/${encodeURIComponent(params.destination_type)}`,
      params: {},
    });
  }

  /**
   * Create creates an event log streaming config for an environment.
   * @param data {@link CreateRequest}
   * @returns {@link CreateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async create(data: CreateRequest): Promise<CreateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<CreateResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/event_log_streaming`,
      data: {
        destination_type: data.destination_type,
        destination_config: data.destination_config,
      },
    });
  }

  /**
   * Update updates an event log streaming config for an environment.
   * @param data {@link UpdateRequest}
   * @returns {@link UpdateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async update(data: UpdateRequest): Promise<UpdateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!data.destination_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "destination_type cannot be empty"
      );
    }
    return request<UpdateResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/event_log_streaming/${encodeURIComponent(data.destination_type)}`,
      data: {
        destination_config: data.destination_config,
      },
    });
  }

  /**
   * Delete deletes an event log streaming config for an environment.
   * @param data {@link DeleteRequest}
   * @returns {@link DeleteResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async delete(data: DeleteRequest): Promise<DeleteResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!data.destination_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "destination_type cannot be empty"
      );
    }
    return request<DeleteResponse>(this.fetchConfig, {
      method: "DELETE",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/event_log_streaming/${encodeURIComponent(data.destination_type)}`,
      data: {},
    });
  }

  /**
   * Enable starts streaming event logs for an environment to a destination.
   * @param data {@link EnableRequest}
   * @returns {@link EnableResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async enable(data: EnableRequest): Promise<EnableResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!data.destination_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "destination_type cannot be empty"
      );
    }
    return request<EnableResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/event_log_streaming/${encodeURIComponent(
        data.destination_type
      )}/enable`,
      data: {},
    });
  }

  /**
   * Disable stops streaming event logs for an environment to a destination.
   * @param data {@link DisableRequest}
   * @returns {@link DisableResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async disable(data: DisableRequest): Promise<DisableResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!data.destination_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "destination_type cannot be empty"
      );
    }
    return request<DisableResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/event_log_streaming/${encodeURIComponent(
        data.destination_type
      )}/disable`,
      data: {},
    });
  }
}
