// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ManagementClient } from "./client";
export { ManagementClient };
export { ClientConfig } from "./shared/client";
export * from "./shared/errors";

// Export resource modules as namespaces to avoid type name conflicts
export * as projects from "./projects";
export * as country_code_allowlist from "./country_code_allowlist";
export * as emailtemplates from "./emailtemplates";
export * as environments from "./environments";
export * as event_log_streaming from "./event_log_streaming";
export * as jwttemplates from "./jwttemplates";
export * as passwordstrengthconfig from "./passwordstrengthconfig";
export * as publictokens from "./publictokens";
export * as rbacpolicy from "./rbacpolicy";
export * as redirecturls from "./redirecturls";
export * as sdk from "./sdk";
export * as secrets from "./secrets";
export * as trustedtokenprofiles from "./trustedtokenprofiles";

export default ManagementClient;
