// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface JWTTemplate {
  // TemplateContent is the JWT template content.
  template_content: string;
  // CustomAudience is an optional custom audience for the JWT template.
  custom_audience: string;
  // JWTTemplateType is the type of JWT template.
  jwt_template_type?: "SESSION" | "M2M" | string;
}

// Request type for `jwtTemplates.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // JWTTemplateType is the type of JWT template.
  jwt_template_type?: "SESSION" | "M2M" | string;
}

// Response type for `jwtTemplates.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // JWTTemplate is the JWT template for the requested JWTTemplateType.
  jwt_template: JWTTemplate;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `jwtTemplates.set`.
export interface SetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // TemplateContent is the JWT template content.
  template_content: string;
  // CustomAudience is an optional custom audience for the JWT template.
  custom_audience: string;
  // JWTTemplateType is the type of JWT template.
  jwt_template_type?: "SESSION" | "M2M" | string;
}

// Response type for `jwtTemplates.set`.
export interface SetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // JWTTemplate is the JWT template for the requested JWTTemplateType.
  jwt_template: JWTTemplate;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class JWTTemplates {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Get retrieves a JWT template for a project
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!params.jwt_template_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "jwt_template_type cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/jwt_templates/${encodeURIComponent(params.jwt_template_type)}`,
      params: {},
    });
  }

  /**
   * Set updates a specific JWT template for a project
   * @param data {@link SetRequest}
   * @returns {@link SetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async set(data: SetRequest): Promise<SetResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!data.jwt_template_type) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "jwt_template_type cannot be empty"
      );
    }
    return request<SetResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/jwt_templates/${encodeURIComponent(data.jwt_template_type)}`,
      data: {
        template_content: data.template_content,
        custom_audience: data.custom_audience,
      },
    });
  }
}
