// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface PasswordStrengthConfig {
  /**
   * CheckBreachOnCreation is a flag to check whether to use the HaveIBeenPwned database to detect password
   * breaches when a user first creates their password.
   */
  check_breach_on_creation: boolean;
  /**
   * CheckBreachOnAuthentication denotes whether to use the HaveIBeenPwned database to detect password
   * breaches when a user authenticates.
   */
  check_breach_on_authentication: boolean;
  /**
   * ValidateOnAuthentication notes whether to require a password reset on authentication if a user's current
   * password no longer meets the project's current policy requirements.
   */
  validate_on_authentication: boolean;
  // ValidationPolicy is the policy to use for password validation.
  validation_policy?:
    | "ValidationPolicyZXCVBN"
    | "ValidationPolicyLUDS"
    | string;
  /**
   * LudsMinPasswordLength is the minimum number of characters in a password if using a LUDS
   * validation_policy. This field is nil when using the ZXCVBN validation_policy.
   */
  luds_min_password_length?: number;
  /**
   * LudsMinPasswordComplexity is the minimum number of "character types" in a password (Lowercase,
   * Uppercase, Digits, Symbols) when using a LUDS validation_policy. This field is nil when using the ZXCVBN
   * validation_policy.
   */
  luds_min_password_complexity?: number;
}

// Request type for `passwordStrengthConfig.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `passwordStrengthConfig.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // PasswordStrengthConfig is the password strength configuration for the environment.
  password_strength_config: PasswordStrengthConfig;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `passwordStrengthConfig.set`.
export interface SetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  /**
   * CheckBreachOnCreation is a flag to check whether to use the HaveIBeenPwned database to detect password
   * breaches when a user first creates their password.
   */
  check_breach_on_creation: boolean;
  /**
   * CheckBreachOnAuthentication denotes whether to use the HaveIBeenPwned database to detect password
   * breaches when a user authenticates.
   */
  check_breach_on_authentication: boolean;
  /**
   * ValidateOnAuthentication notes whether to require a password reset on authentication if a user's current
   * password no longer meets the project's current policy requirements.
   */
  validate_on_authentication: boolean;
  // ValidationPolicy is the policy to use for password validation.
  validation_policy?:
    | "ValidationPolicyZXCVBN"
    | "ValidationPolicyLUDS"
    | string;
  /**
   * LudsMinPasswordLength is the minimum number of characters in a password if using a LUDS
   * validation_policy. This field is nil when using the ZXCVBN validation_policy.
   */
  luds_min_password_length?: number;
  /**
   * LudsMinPasswordComplexity is the minimum number of "character types" in a password (Lowercase,
   * Uppercase, Digits, Symbols) when using a LUDS validation_policy. This field is nil when using the ZXCVBN
   * validation_policy.
   */
  luds_min_password_complexity?: number;
}

// Response type for `passwordStrengthConfig.set`.
export interface SetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // PasswordStrengthConfig is the password strength configuration for the environment.
  password_strength_config: PasswordStrengthConfig;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class PasswordStrengthConfig {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Get retrieves the password strength configuration for an environment.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/password_strength_config`,
      params: {},
    });
  }

  /**
   * Set updates the password strength configuration for an environment.
   * @param data {@link SetRequest}
   * @returns {@link SetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async set(data: SetRequest): Promise<SetResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<SetResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/password_strength_config`,
      data: {
        check_breach_on_creation: data.check_breach_on_creation,
        check_breach_on_authentication: data.check_breach_on_authentication,
        validate_on_authentication: data.validate_on_authentication,
        validation_policy: data.validation_policy,
        luds_min_password_length: data.luds_min_password_length,
        luds_min_password_complexity: data.luds_min_password_complexity,
      },
    });
  }
}
