// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface Project {
  // The slug of the project.
  project_slug: string;
  // Name is a human-readable name. This does not have to be unique.
  name: string;
  // Vertical is the project's vertical.
  vertical?: "ALL" | "CONSUMER" | "B2B" | string;
  // The ISO-8601 timestamp for when the resource was created.
  created_at?: string;
}

// Request type for `projects.create`.
export interface CreateRequest {
  // Name is a human-readable name. This does not have to be unique.
  name: string;
  // Vertical is the project's vertical.
  vertical?: "ALL" | "CONSUMER" | "B2B" | string;
  // The slug of the project.
  project_slug?: string;
}

// Response type for `projects.create`.
export interface CreateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Project contains the details for the newly created project.
  project: Project;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `projects.delete`.
export interface DeleteRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
}

// Response type for `projects.delete`.
export interface DeleteResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Response type for `projects.getAll`.
export interface GetAllResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Projects is a list of all active projects in the workspace.
  projects: Project[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `projects.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
}

// Response type for `projects.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Project contains the project details.
  project: Project;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `projects.update`.
export interface UpdateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // Name is a human-readable name. This does not have to be unique.
  name?: string;
}

// Response type for `projects.update`.
export interface UpdateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Project contains the updated project details.
  project: Project;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class Projects {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Create creates a project, including both a live and test environment.
   * @param data {@link CreateRequest}
   * @returns {@link CreateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async create(data: CreateRequest): Promise<CreateResponse> {
    return request<CreateResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects`,
      data,
    });
  }

  /**
   * Get retrieves a project.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(params.project_slug)}`,
      params: {},
    });
  }

  /**
   * GetAll retrieves all projects in a workspace.
   * @param params {@link GetAllRequest}
   * @returns {@link GetAllResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getAll(): Promise<GetAllResponse> {
    return request<GetAllResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects`,
    });
  }

  /**
   * Update updates the project.
   * @param data {@link UpdateRequest}
   * @returns {@link UpdateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async update(data: UpdateRequest): Promise<UpdateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    return request<UpdateResponse>(this.fetchConfig, {
      method: "PATCH",
      url: `/pwa/v3/projects/${encodeURIComponent(data.project_slug)}`,
      data: {
        name: data.name,
      },
    });
  }

  /**
   * Delete deletes a project and all of its environments.
   * @param data {@link DeleteRequest}
   * @returns {@link DeleteResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async delete(data: DeleteRequest): Promise<DeleteResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    return request<DeleteResponse>(this.fetchConfig, {
      method: "DELETE",
      url: `/pwa/v3/projects/${encodeURIComponent(data.project_slug)}`,
      data: {},
    });
  }
}
