// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface PublicToken {
  // The public token value as well as the unique identifier for the token.
  public_token: string;
  // The ISO-8601 timestamp for when the resource was created.
  created_at?: string;
}

// Request type for `publicTokens.create`.
export interface CreateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `publicTokens.create`.
export interface CreateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Contains details about the public token object.
  public_token: PublicToken;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `publicTokens.delete`.
export interface DeleteRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The public token to delete.
  public_token: string;
}

// Response type for `publicTokens.delete`.
export interface DeleteResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `publicTokens.getAll`.
export interface GetAllRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `publicTokens.getAll`.
export interface GetAllResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // All the public tokens that belong to the environment.
  public_tokens: PublicToken[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `publicTokens.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The identifier of the public token to retrieve.
  public_token: string;
}

// Response type for `publicTokens.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Contains details about the public token object.
  public_token: PublicToken;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class PublicTokens {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Create creates a new public token for an environment.
   * @param data {@link CreateRequest}
   * @returns {@link CreateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async create(data: CreateRequest): Promise<CreateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<CreateResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/public_tokens`,
      data: {},
    });
  }

  /**
   * Get retrieves a public token for an environment.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!params.public_token) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "public_token cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/public_tokens/${encodeURIComponent(params.public_token)}`,
      params: {},
    });
  }

  /**
   * GetAll retrieves all the active public tokens defined for an environment.
   * @param params {@link GetAllRequest}
   * @returns {@link GetAllResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getAll(params: GetAllRequest): Promise<GetAllResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetAllResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/public_tokens`,
      params: {},
    });
  }

  /**
   * Delete deletes a public token for an environment.
   * @param data {@link DeleteRequest}
   * @returns {@link DeleteResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async delete(data: DeleteRequest): Promise<DeleteResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    if (!data.public_token) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "public_token cannot be empty"
      );
    }
    return request<DeleteResponse>(this.fetchConfig, {
      method: "DELETE",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/public_tokens/${encodeURIComponent(data.public_token)}`,
      data: {},
    });
  }
}
