// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface DefaultRole {
  // Permissions are the permissions granted to this role for resources within the environment.
  permissions: Permission[];
}

export interface Permission {
  // ResourceID is a human-readable name that is unique within the environment.
  resource_id: string;
  // Actions is an array of actions that the role can perform on the given resource.
  actions: string[];
}

export interface Policy {
  /**
   * StytchResources consists of resources created by Stytch that always exist. This field will be returned
   * in relevant Policy objects but can never be overridden or deleted.
   */
  stytch_resources: Resource[];
  /**
   * The following fields are valid for both B2B and Consumer projects: CustomRoles are additional roles that
   * exist within the environment beyond the stytch_member, stytch_admin, or stytch_user roles.
   */
  custom_roles: Role[];
  /**
   * CustomResources are resources that exist within the environment beyond those defined within the
   * stytch_resources.
   */
  custom_resources: Resource[];
  // CustomScopes are additional scopes that exist within the environment beyond those defined by default.
  custom_scopes: Scope[];
  /**
   * The following fields are valid for B2B projects only: StytchMember is the default role given to members
   * within the environment. Only permissions are returned; role_id and description are managed by Stytch.
   */
  stytch_member?: DefaultRole;
  /**
   * StytchAdmin is the role assigned to admins within an organization. Only permissions are returned;
   * role_id and description are managed by Stytch.
   */
  stytch_admin?: DefaultRole;
  /**
   * The following field is valid for Consumer projects only: StytchUser is the default role given to users
   * within the environment. Only permissions are returned; role_id and description are managed by Stytch.
   */
  stytch_user?: DefaultRole;
}

export interface Resource {
  // ResourceID is a human-readable name that is unique within the environment.
  resource_id: string;
  // Description is a description for the role.
  description: string;
  // AvailableActions are the actions that can be granted for this resource.
  available_actions: string[];
}

export interface Role {
  // RoleID is a human-readable name that is unique within the environment.
  role_id: string;
  // Description is a description for the role.
  description: string;
  // Permissions are the permissions granted to this role for resources within the environment.
  permissions: Permission[];
}

export interface Scope {
  // Scope is a human-readable name that is unique within the environment.
  scope: string;
  // Description is a description for the role.
  description: string;
  // Permissions are the permissions granted to this role for resources within the environment.
  permissions: Permission[];
}

// Request type for `rbacPolicy.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `rbacPolicy.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Policy is the RBAC policy for the environment.
  policy: Policy;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `rbacPolicy.set`.
export interface SetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  /**
   * The following fields are valid for B2B projects only: StytchMember is the default role given to members
   * within the environment. Only permissions are returned; role_id and description are managed by Stytch.
   */
  stytch_member?: DefaultRole;
  /**
   * StytchAdmin is the role assigned to admins within an organization. Only permissions are returned;
   * role_id and description are managed by Stytch.
   */
  stytch_admin?: DefaultRole;
  /**
   * The following field is valid for Consumer projects only: StytchUser is the default role given to users
   * within the environment. Only permissions are returned; role_id and description are managed by Stytch.
   */
  stytch_user?: DefaultRole;
  /**
   * The following fields are valid for both B2B and Consumer projects: CustomRoles are additional roles that
   * exist within the environment beyond the stytch_member, stytch_admin, or stytch_user roles.
   */
  custom_roles?: Role[];
  /**
   * CustomResources are resources that exist within the environment beyond those defined within the
   * stytch_resources.
   */
  custom_resources?: Resource[];
  // CustomScopes are additional scopes that exist within the environment beyond those defined by default.
  custom_scopes?: Scope[];
}

// Response type for `rbacPolicy.set`.
export interface SetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Policy is the RBAC policy for the environment.
  policy: Policy;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class RBACPolicy {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Get retrieves the RBAC policy for an environment.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/rbac_policy`,
      params: {},
    });
  }

  /**
   * Set updates the RBAC policy for an environment.
   * @param data {@link SetRequest}
   * @returns {@link SetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async set(data: SetRequest): Promise<SetResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<SetResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(data.environment_slug)}/rbac_policy`,
      data: {
        stytch_member: data.stytch_member,
        stytch_admin: data.stytch_admin,
        stytch_user: data.stytch_user,
        custom_roles: data.custom_roles,
        custom_resources: data.custom_resources,
        custom_scopes: data.custom_scopes,
      },
    });
  }
}
