// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface RedirectURL {
  // The URL to which to redirect.
  url: string;
  // ValidTypes is a list of all the URLRedirectType available for this URL.
  valid_types: URLType[];
}

export interface URLType {
  // IsDefault is true if this is the default redirect type, false otherwise.
  is_default: boolean;
  // One of the RedirectType values.
  type?:
    | "LOGIN"
    | "INVITE"
    | "SIGNUP"
    | "RESET_PASSWORD"
    | "DISCOVERY"
    | string;
}

// Request type for `redirectURLs.create`.
export interface CreateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The URL to which to redirect.
  url: string;
  // ValidTypes is a list of all the URLRedirectType available for this URL.
  valid_types?: URLType[];
  /**
   * DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no
   * other RedirectURL exists for the given type. This is primarily intended for use with
   * stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create
   * request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL
   * exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is
   * possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no
   * default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic
   * link), you will need to explicitly specify which redirect URL should be used.
   */
  do_not_promote_defaults?: boolean;
}

// Response type for `redirectURLs.create`.
export interface CreateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // RedirectURL is the object that was created.
  redirect_url: RedirectURL;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `redirectURLs.delete`.
export interface DeleteRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The URL to which to redirect.
  url: string;
  /**
   * DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no
   * other RedirectURL exists for the given type. This is primarily intended for use with
   * stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create
   * request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL
   * exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is
   * possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no
   * default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic
   * link), you will need to explicitly specify which redirect URL should be used.
   */
  do_not_promote_defaults?: boolean;
}

// Response type for `redirectURLs.delete`.
export interface DeleteResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `redirectURLs.getAll`.
export interface GetAllRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `redirectURLs.getAll`.
export interface GetAllResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // RedirectURLs is a list of all the redirect URLs for the project.
  redirect_urls: RedirectURL[];
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `redirectURLs.get`.
export interface GetRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The URL to which to redirect.
  url: string;
}

// Response type for `redirectURLs.get`.
export interface GetResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // RedirectURL is the redirect URL.
  redirect_url: RedirectURL;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `redirectURLs.update`.
export interface UpdateRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // The URL to which to redirect.
  url: string;
  // ValidTypes is a list of all the URLRedirectType available for this URL.
  valid_types?: URLType[];
  /**
   * DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no
   * other RedirectURL exists for the given type. This is primarily intended for use with
   * stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create
   * request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL
   * exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is
   * possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no
   * default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic
   * link), you will need to explicitly specify which redirect URL should be used.
   */
  do_not_promote_defaults?: boolean;
}

// Response type for `redirectURLs.update`.
export interface UpdateResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // RedirectURL is the object that was updated.
  redirect_url: RedirectURL;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class RedirectURLs {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * Create creates a redirect URL for an environment.
   * @param data {@link CreateRequest}
   * @returns {@link CreateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async create(data: CreateRequest): Promise<CreateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<CreateResponse>(this.fetchConfig, {
      method: "POST",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/redirect_urls`,
      data: {
        url: data.url,
        valid_types: data.valid_types,
        do_not_promote_defaults: data.do_not_promote_defaults,
      },
    });
  }

  /**
   * Get retrieves a redirect URL for an environment.
   * @param params {@link GetRequest}
   * @returns {@link GetResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async get(params: GetRequest): Promise<GetResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/redirect_urls`,
      params: {
        url: params.url,
      } as Record<string, string | number | boolean | undefined>,
    });
  }

  /**
   * GetAll retrieves all redirect URLs for an environment.
   * @param params {@link GetAllRequest}
   * @returns {@link GetAllResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getAll(params: GetAllRequest): Promise<GetAllResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetAllResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/redirect_urls/all`,
      params: {},
    });
  }

  /**
   * Update updates the valid types for a redirect URL for an environment.
   * @param data {@link UpdateRequest}
   * @returns {@link UpdateResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async update(data: UpdateRequest): Promise<UpdateResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<UpdateResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/redirect_urls`,
      data: {
        valid_types: data.valid_types,
        do_not_promote_defaults: data.do_not_promote_defaults,
      },
      params: {
        url: data.url,
      } as Record<string, string | number | boolean | undefined>,
    });
  }

  /**
   * Delete deletes a redirect URL for an environment.
   * @param data {@link DeleteRequest}
   * @returns {@link DeleteResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async delete(data: DeleteRequest): Promise<DeleteResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<DeleteResponse>(this.fetchConfig, {
      method: "DELETE",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/redirect_urls`,
      params: {
        url: data.url,
        do_not_promote_defaults: data.do_not_promote_defaults,
      } as Record<string, string | number | boolean | undefined>,
    });
  }
}
