// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import { ClientError } from "./shared/errors";
import { fetchConfig } from "./shared";
import { request } from "./shared";

export interface AuthorizedB2BDomain {
  // Domain is the domain name. Stytch uses the same-origin policy to determine matches.
  domain: string;
  /**
   * SlugPattern is the slug pattern that can be used to support authentication flows specific to each
   * organization. An example value here might be 'https://{{slug}}.example.com'. The value **must** include
   * '{{slug}}' as a placeholder for the slug.
   */
  slug_pattern: string;
}

export interface B2BBasicConfig {
  /**
   * Enabled indicates whether the B2B project SDK is enabled. This allows the SDK to manage user and session
   * data.
   */
  enabled: boolean;
  // AllowSelfOnboarding indicates whether self-onboarding is allowed for members in the SDK.
  allow_self_onboarding: boolean;
  // EnableMemberPermissions indicates whether member permissions RBAC are enabled in the SDK.
  enable_member_permissions: boolean;
  // Domains is a list of domains authorized for use in the SDK.
  domains: AuthorizedB2BDomain[];
  // BundleIDs is a list of bundle IDs authorized for use in the SDK.
  bundle_ids: string[];
}

export interface B2BConfig {
  // The basic configuration for the SDK. This includes enabling the SDK.
  basic?: B2BBasicConfig;
  // The session configuration for the SDK.
  sessions?: B2BSessionsConfig;
  // The magic links configuration for the SDK.
  magic_links?: B2BMagicLinksConfig;
  // The OAuth configuration for the SDK.
  oauth?: B2BOAuthConfig;
  // TOTPs is the TOTPs configuration for the SDK.
  totps?: B2BTOTPsConfig;
  // SSO is the SSO configuration for the B2B project SDK.
  sso?: B2BSSOConfig;
  // OTPs is the OTPs configuration for the SDK.
  otps?: B2BOTPsConfig;
  // DFPPA is the Device Fingerprinting Protected Auth configuration for the SDK.
  DFPPA?: B2BDFPPAConfig;
  // Passwords is the passwords configuration for the SDK.
  passwords?: B2BPasswordsConfig;
  // Cookies is the cookies configuration for the SDK.
  cookies?: B2BCookiesConfig;
}

export interface B2BCookiesConfig {
  // Specifies whether cookies should be set with the HttpOnly flag.
  http_only: "DISABLED" | "ENABLED" | "ENFORCED" | string;
}

export interface B2BDFPPAConfig {
  // Indicates whether Device Fingerprinting Protected Auth endpoints are enabled in the SDK.
  enabled?: "ENABLED" | "PASSIVE" | "DISABLED" | string;
  // OnChallenge is the action to take when a DFPPA "challenge" verdict is returned.
  on_challenge?: "ALLOW" | "BLOCK" | "TRIGGER_CAPTCHA" | string;
}

export interface B2BMagicLinksConfig {
  // Indicates whether Magic Links endpoints are enabled in the SDK.
  enabled: boolean;
  /**
   * Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required: boolean;
}

export interface B2BOAuthConfig {
  // Indicates whether OAuth endpoints are enabled in the SDK.
  enabled: boolean;
  /**
   * Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required: boolean;
}

export interface B2BOTPsConfig {
  // SMSEnabled indicates whether the SMS OTP endpoints are enabled in the SDK.
  sms_enabled: boolean;
  // SMSAutofillMetadata is a list of metadata that can be used for autofill of SMS OTPs.
  sms_autofill_metadata: SMSAutofillMetadata[];
  // EmailEnabled indicates whether the email OTP endpoints are enabled in the SDK.
  email_enabled: boolean;
}

export interface B2BPasswordsConfig {
  // Indicates whether Passwords endpoints are enabled in the SDK.
  enabled: boolean;
  /**
   * PKCERequired indicates whether PKCE is required for password resets. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required_for_password_resets: boolean;
}

export interface B2BSSOConfig {
  // Indicates whether SSO endpoints are enabled in the SDK.
  enabled: boolean;
  /**
   * Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required: boolean;
}

export interface B2BSessionsConfig {
  // MaxSessionDurationMinutes is the maximum session duration that can be created in minutes.
  max_session_duration_minutes: number;
}

export interface B2BTOTPsConfig {
  // CreateTOTPs indicates whether TOTP creation is enabled in the SDK.
  create_totps: boolean;
  // Indicates whether TOTP endpoints are enabled in the SDK.
  enabled: boolean;
}

export interface ConsumerBasicConfig {
  /**
   * Enabled indicates whether the consumer project SDK is enabled. This allows the SDK to manage user and
   * session data.
   */
  enabled: boolean;
  // Domains is a list of domains authorized for use in the SDK.
  domains: string[];
  // BundleIDs is a list of bundle IDs authorized for use in the SDK.
  bundle_ids: string[];
}

export interface ConsumerBiometricsConfig {
  // CreateBiometricsEnabled indicates whether biometrics creation is enabled in the SDK.
  create_biometrics_enabled: boolean;
  /**
   * Enabled indicates whether the consumer project SDK is enabled. This allows the SDK to manage user and
   * session data.
   */
  enabled: boolean;
}

export interface ConsumerConfig {
  // The basic configuration for the SDK. This includes enabling the SDK.
  basic?: ConsumerBasicConfig;
  // The session configuration for the SDK.
  sessions?: ConsumerSessionsConfig;
  // The magic links configuration for the SDK.
  magic_links?: ConsumerMagicLinksConfig;
  // OTPs is the OTPs configuration for the SDK.
  otps?: ConsumerOTPsConfig;
  // The OAuth configuration for the SDK.
  oauth?: ConsumerOAuthConfig;
  // TOTPs is the TOTPs configuration for the SDK.
  totps?: ConsumerTOTPsConfig;
  // WebAuthn is the WebAuthn configuration for the SDK.
  webauthn?: ConsumerWebAuthnConfig;
  // CryptoWallets is the Crypto Wallets configuration for the SDK.
  crypto_wallets?: ConsumerCryptoWalletsConfig;
  // DFPPA is the Device Fingerprinting Protected Auth configuration for the SDK.
  DFPPA?: ConsumerDFPPAConfig;
  // Biometrics is the biometrics configuration for the SDK.
  biometrics?: ConsumerBiometricsConfig;
  // Passwords is the passwords configuration for the SDK.
  passwords?: ConsumerPasswordsConfig;
  // Cookies is the cookies configuration for the SDK.
  cookies?: ConsumerCookiesConfig;
}

export interface ConsumerCookiesConfig {
  // Specifies whether cookies should be set with the HttpOnly flag.
  http_only: "DISABLED" | "ENABLED" | "ENFORCED" | string;
}

export interface ConsumerCryptoWalletsConfig {
  // Indicates whether Crypto Wallets endpoints are enabled in the SDK.
  enabled: boolean;
  // SIWERequired indicates whether Sign In With Ethereum is required for Crypto Wallets.
  siwe_required: boolean;
}

export interface ConsumerDFPPAConfig {
  // Indicates whether Device Fingerprinting Protected Auth endpoints are enabled in the SDK.
  enabled?: "ENABLED" | "PASSIVE" | "DISABLED" | string;
  // OnChallenge is the action to take when a DFPPA "challenge" verdict is returned.
  on_challenge?: "ALLOW" | "BLOCK" | "TRIGGER_CAPTCHA" | string;
}

export interface ConsumerMagicLinksConfig {
  // LoginOrCreateEnabled indicates whether login-or-create with magic links is enabled in the SDK.
  login_or_create_enabled: boolean;
  // SendEnabled indicates whether the magic links send endpoint is enabled in the SDK.
  send_enabled: boolean;
  /**
   * Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required: boolean;
}

export interface ConsumerOAuthConfig {
  // Indicates whether OAuth endpoints are enabled in the SDK.
  enabled: boolean;
  /**
   * Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required: boolean;
}

export interface ConsumerOTPsConfig {
  // SMSLoginOrCreateEnabled indicates whether the SMS OTP login or create endpoint is enabled in the SDK.
  sms_login_or_create_enabled: boolean;
  /**
   * WhatsAppLoginOrCreateEnabled indicates whether the WhatsApp OTP login or create endpoint is enabled in
   * the SDK.
   */
  whatsapp_login_or_create_enabled: boolean;
  // EmailLoginOrCreateEnabled indicates whether the email OTP login or create endpoint is enabled in the SDK.
  email_login_or_create_enabled: boolean;
  // SMSSendEnabled indicates whether the SMS OTP send endpoint is enabled in the SDK.
  sms_send_enabled: boolean;
  // WhatsAppSendEnabled indicates whether the WhatsApp OTP send endpoint is enabled in the SDK.
  whatsapp_send_enabled: boolean;
  // EmailSendEnabled indicates whether the email OTP send endpoint is enabled in the SDK.
  email_send_enabled: boolean;
  // SMSAutofillMetadata is a list of metadata that can be used for autofill of SMS OTPs.
  sms_autofill_metadata: SMSAutofillMetadata[];
}

export interface ConsumerPasswordsConfig {
  // Indicates whether Passwords endpoints are enabled in the SDK.
  enabled: boolean;
  /**
   * PKCERequired indicates whether PKCE is required for password resets. PKCE increases security by
   * introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow
   * from the same application on the device. This prevents a malicious app from intercepting a redirect and
   * authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
   */
  pkce_required_for_password_resets: boolean;
}

export interface ConsumerSessionsConfig {
  // MaxSessionDurationMinutes is the maximum session duration that can be created in minutes.
  max_session_duration_minutes: number;
}

export interface ConsumerTOTPsConfig {
  // CreateTOTPs indicates whether TOTP creation is enabled in the SDK.
  create_totps: boolean;
  // Indicates whether TOTP endpoints are enabled in the SDK.
  enabled: boolean;
}

export interface ConsumerWebAuthnConfig {
  create_webauthns: boolean;
  // Indicates whether WebAuthn endpoints are enabled in the SDK.
  enabled: boolean;
}

export interface SMSAutofillMetadata {
  // MetadataType is the type of metadata to use for autofill. This should be either "domain" or "hash".
  metadata_type: "domain" | "hash" | string;
  /**
   * MetadataValue is the value of the metadata to use for autofill. This should be the associated domain
   * name (for MetadataType "domain") or application hash (for MetadataType "hash").
   */
  metadata_value: string;
  // BundleID is the ID of the bundle to use for autofill. This should be the associated bundle ID.
  bundle_id: string;
}

// Request type for `sdk.getB2BConfig`.
export interface GetB2BConfigRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `sdk.getB2BConfig`.
export interface GetB2BConfigResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Config is the SDK configuration.
  config: B2BConfig;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `sdk.getConsumerConfig`.
export interface GetConsumerConfigRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
}

// Response type for `sdk.getConsumerConfig`.
export interface GetConsumerConfigResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Config is the SDK configuration.
  config: ConsumerConfig;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `sdk.setB2BConfig`.
export interface SetB2BConfigRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // Config is the SDK configuration.
  config?: B2BConfig;
}

// Response type for `sdk.setB2BConfig`.
export interface SetB2BConfigResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Config is the SDK configuration.
  config: B2BConfig;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

// Request type for `sdk.setConsumerConfig`.
export interface SetConsumerConfigRequest {
  // ProjectSlug is the slug of the project.
  project_slug: string;
  // EnvironmentSlug is the slug of the environment.
  environment_slug: string;
  // Config is the SDK configuration.
  config?: ConsumerConfig;
}

// Response type for `sdk.setConsumerConfig`.
export interface SetConsumerConfigResponse {
  // RequestID is a unique identifier to help with debugging the request.
  request_id: string;
  // Config is the SDK configuration.
  config: ConsumerConfig;
  // StatusCode is the HTTP status code for the response.
  status_code: number;
}

export class SDK {
  private fetchConfig: fetchConfig;

  constructor(fetchConfig: fetchConfig) {
    this.fetchConfig = fetchConfig;
  }

  /**
   * GetConsumerConfig retrieves the SDK configuration for a B2C project environment
   * @param params {@link GetConsumerConfigRequest}
   * @returns {@link GetConsumerConfigResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getConsumerConfig(
    params: GetConsumerConfigRequest
  ): Promise<GetConsumerConfigResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetConsumerConfigResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(
        params.environment_slug
      )}/sdk/consumer`,
      params: {},
    });
  }

  /**
   * SetConsumerConfig updates the SDK configuration for a B2C project environment
   * @param data {@link SetConsumerConfigRequest}
   * @returns {@link SetConsumerConfigResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async setConsumerConfig(
    data: SetConsumerConfigRequest
  ): Promise<SetConsumerConfigResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<SetConsumerConfigResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(
        data.environment_slug
      )}/sdk/consumer`,
      data: {
        config: data.config,
      },
    });
  }

  /**
   * GetB2BConfig retrieves the SDK configuration for a B2B project environment
   * @param params {@link GetB2BConfigRequest}
   * @returns {@link GetB2BConfigResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async getB2BConfig(
    params: GetB2BConfigRequest
  ): Promise<GetB2BConfigResponse> {
    if (!params.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!params.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<GetB2BConfigResponse>(this.fetchConfig, {
      method: "GET",
      url: `/pwa/v3/projects/${encodeURIComponent(
        params.project_slug
      )}/environments/${encodeURIComponent(params.environment_slug)}/sdk/b2b`,
      params: {},
    });
  }

  /**
   * SetB2BConfig updates the SDK configuration for a B2B project environment
   * @param data {@link SetB2BConfigRequest}
   * @returns {@link SetB2BConfigResponse}
   * @async
   * @throws A {@link StytchError} on a non-2xx response from the Stytch API
   * @throws A {@link RequestError} when the Stytch API cannot be reached
   */
  async setB2BConfig(data: SetB2BConfigRequest): Promise<SetB2BConfigResponse> {
    if (!data.project_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "project_slug cannot be empty"
      );
    }
    if (!data.environment_slug) {
      throw new ClientError(
        "MISSING_PATH_PARAMETER",
        "environment_slug cannot be empty"
      );
    }
    return request<SetB2BConfigResponse>(this.fetchConfig, {
      method: "PUT",
      url: `/pwa/v3/projects/${encodeURIComponent(
        data.project_slug
      )}/environments/${encodeURIComponent(data.environment_slug)}/sdk/b2b`,
      data: {
        config: data.config,
      },
    });
  }
}
